FROM mcr.microsoft.com/dotnet/runtime:3.1 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src
COPY ["PatientDataConsumer/PatientDataConsumer.csproj", "PatientDataConsumer/"]
COPY ["Api.DAL/Api.DAL.csproj", "Api.DAL/"]
RUN dotnet restore "PatientDataConsumer/PatientDataConsumer.csproj"
COPY . .
WORKDIR "/src/PatientDataConsumer"
RUN dotnet build "PatientDataConsumer.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "PatientDataConsumer.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "PatientDataConsumer.dll"]
