FROM mcr.microsoft.com/dotnet/runtime:3.1 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src
COPY ["DoctorDataConsumer/DoctorDataConsumer.csproj", "DoctorDataConsumer/"]
COPY ["Api.DAL/Api.DAL.csproj", "Api.DAL/"]
RUN dotnet restore "DoctorDataConsumer/DoctorDataConsumer.csproj"
COPY . .
WORKDIR "/src/DoctorDataConsumer"
RUN dotnet build "DoctorDataConsumer.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "DoctorDataConsumer.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "DoctorDataConsumer.dll"]
