FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src
COPY ["PatientApi/PatientApi.csproj", "PatientApi/"]
COPY ["Api.DAL/Api.DAL.csproj", "Api.DAL/"]
COPY ["Api.Models/Api.Models.csproj", "Api.Models/"]
RUN dotnet restore "PatientApi/PatientApi.csproj"
COPY . .
WORKDIR "/src/PatientApi"
RUN dotnet build "PatientApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "PatientApi.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "PatientApi.dll"]

